create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table kapcsolattarto
(
    id              bigint          generated by default as identity,
    firstName       varchar(250)    not null,
    lastName        varchar(250)    not null,
    email           varchar(250)    not null,
    phone           varchar(30),
    company_id      bigint          not null,
    comment         varchar(1000),
    status          smallint        not null,
    creation_time   timestamp       not null,
    modified_time   timestamp,
    constraint pk_company primary key (id),
    constraint fk_kapcsolattarto_company foreign key(company_id)
    references company(id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');
